import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  background: {
    flex: 1,
    width,
    height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoContainer: {
    marginTop: height * 0.18,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.11)',
    padding: 14,
    borderRadius: 26,
    shadowColor: '#4445',
    shadowOpacity: 0.13,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 14,
  },
  logoText: {
    fontSize: 38,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    color: '#fff',
    textShadowColor: '#4738a2cc',
    textShadowOffset: { width: 0, height: 5 },
    textShadowRadius: 10,
    textAlign: 'center',
  },
  slogan: {
    fontSize: 19,
    color: '#fff',
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 12,
    textShadowColor: '#171d3fcc',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  buttonWrapper: {
    position: 'absolute',
    bottom: height * 0.13,
    width: '100%',
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#ffbe39',
    paddingVertical: 18,
    paddingHorizontal: 56,
    borderRadius: 32,
    elevation: 4,
    shadowColor: '#ffbf0080',
    shadowOpacity: 0.7,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 14,
    minWidth: 220,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textShadowColor: '#4738a299',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },
});
